website/auth.py
from flask import Blueprint, render_template, request, flash, get_flashed_messages, redirect, url_for  # Importing necessary Flask functions
from .model import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from sqlalchemy import and_, or_, case, not_
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST': 
        data = request.form
        email = data.get('email')
        password = data.get('password')
        if not email or not password:
            flash('complete your data', category='error')
        elif email and not email.endswith('@student.guc.edu.eg'):
            flash('Write your email correctly', category='error')
        else:
            user = User.query.filter_by(email=email).first() 
            if user:
                if check_password_hash(user.password, password):
                    login_user(user, remember=True)  # remember him that he logged in before
                    flash('login successful', category='success')
                    return redirect(url_for('auth.query', user_id=user.id))
                else:
                    flash('Incorrect Password', category='error')
            else:
                flash('email does not exist', category='error')
        return render_template("login.html", boolean=True)
    return render_template("login.html", boolean=True)

@auth.route('/logout')
@login_required 
def logout():
    logout_user() 
    return redirect(url_for('auth.login')) 

@auth.route('/delete')
@login_required
def delete():
    try:
        user = current_user
        db.session.delete(user)
        db.session.commit()
        logout_user()
        flash('Your account has been successfully deleted.', category='success')
    except Exception:
        db.session.rollback()
        flash('An error occurred while deleting your account. Please try again later.', category='error')
    return redirect(url_for('auth.login'))

from flask_login import current_user, login_required



@auth.route('/update', methods=['GET', 'POST'])
@login_required
def update():
    if current_user.is_authenticated:  # Ensure the user is authenticated
        user = current_user  # Get the logged-in user
        if request.method == 'POST':
            # Get updated data from the form
            user.name = request.form['name']
            user.current_group = request.form['current_group']
            user.current_tut = request.form['current_tutorial']
            user.desired_group_1 = request.form['desired_group1']
            user.desired_tut_1 = request.form['desired_tutorial1']
            user.desired_group_2 = request.form['desired_group2']
            user.desired_tut_2 = request.form['desired_tutorial2']
            user.telephone = request.form['phone']
            if int(user.current_group) > 10 or int(user.current_group) < 0 or int(user.desired_group_1) > 10 or int(user.desired_group_1) < 0 or int(user.desired_group_2) > 10 or int(user.desired_group_2) < 0:
                flash('Group must be an integer between 1 and 10.', category='error')
            else:
              db.session.commit()
              flash('Your information has been updated successfully!', 'success')
              return redirect(url_for('auth.query', user_id=user.id))
        return render_template('update.html')
    else:
        flash('You need to be logged in to update your information.', 'danger')
        return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    fields = {
        'email': None,
        'name': None,
        'user_id': None,
        'password': None,
        'phone': None,
        'major': None,
        'semester': None,
        'english': None,
        'german': None,
        'current_group': None,
        'current_tutorial': None,
        'desired_group1': None,
        'desired_tutorial1': None,
        'desired_group2': None,
        'desired_tutorial2': None
    }

    if request.method == 'POST':  # Check if the request method is POST
        # Extract form data
        data = request.form
        fields = {
            'email': data.get('email', None),
            'name': data.get('name', None),
            'user_id': data.get('id', None),
            'password': data.get('password', None),
            'phone': data.get('phone', None),
            'major': data.get('major', None),
            'semester': int(data.get('semester', None)) if data.get('semester') else None,
            'english': data.get('english', None),
            'german': data.get('german', None),
            'current_group': int(data.get('current_group', None)) if data.get('current_group') else None,
            'current_tutorial': int(data.get('current_tutorial', None)) if data.get('current_tutorial') else None,
            'desired_group1': int(data.get('desired_group1', None)) if data.get('desired_group1') else None,
            'desired_tutorial1': int(data.get('desired_tutorial1', None)) if data.get('desired_tutorial1') else None,
            'desired_group2': int(data.get('desired_group2', None)) if data.get('desired_group2') else None,
            'desired_tutorial2': int(data.get('desired_tutorial2', None)) if data.get('desired_tutorial2') else None
        }

        flash_message_set = False  # Flag to check if a flash message is already set

        # Check if email already exists
        user = User.query.filter_by(email=fields['email']).first()
        if user and not flash_message_set:
            flash('Email already exists', category='error')
            flash_message_set = True
        
        existing_user = User.query.filter_by(user_id=fields['user_id']).first()
        if existing_user and not flash_message_set:
            flash('User with this ID already exists!', 'error')
            flash_message_set = True  
        
        # Form validation logic
        for field, value in fields.items():
            if value is None or value == '':
                if not flash_message_set:
                    flash(f'{field.replace("_", " ").capitalize()} is required.', category='error')
                    flash_message_set = True
                break

        # Email validation
        if fields['email'] and not fields['email'].endswith('@student.guc.edu.eg'):
            if not flash_message_set:
                flash('Email must end with @student.guc.edu.eg', category='error')
                flash_message_set = True
        
        # Password validation
        elif fields['password'] and len(fields['password']) < 6:
            if not flash_message_set:
                flash('Password must be at least 6 characters long.', category='error')
                flash_message_set = True
        
        # Group validation (ensure values are integers and between 1-10)
        elif (fields['current_group'] and (fields['current_group'] < 0 or fields['current_group'] > 10)) or \
             (fields['desired_group1'] and (fields['desired_group1'] < 0 or fields['desired_group1'] > 10)) or \
             (fields['desired_group2'] and (fields['desired_group2'] < 0 or fields['desired_group2'] > 10)):
            if not flash_message_set:
                flash('Group must be an integer between 1 and 10.', category='error')
                flash_message_set = True

        # If there are no flash messages, proceed with user creation
        if not flash_message_set:  # Only proceed if no flash message has been triggered
            new_user = User(name=fields['name'], email=fields['email'], telephone=fields['phone'], major=fields['major'],
                            semester=fields['semester'], english_level=fields['english'], german_level=fields['german'],
                            current_group=fields['current_group'], current_tut=fields['current_tutorial'],
                            desired_group_1=fields['desired_group1'], desired_tut_1=fields['desired_tutorial1'],
                            desired_group_2=fields['desired_group2'], desired_tut_2=fields['desired_tutorial2'],
                            password=generate_password_hash(fields['password'], method='pbkdf2:sha256'), user_id=fields['user_id'])
            db.session.add(new_user)
            db.session.commit()
            flash('Account successfully created!', category='success')
            login_user(new_user, remember=True)  # remember him that he logged in before
            return redirect(url_for('auth.login'))  # Redirect to login after successful signup

        # If there are flash messages, pass the entered data back to the template
        return render_template("sign_up.html", data=fields)

    # Handle GET request (when the form is first accessed)
    return render_template("sign_up.html", data=fields)

@auth.route('/query', methods=['GET'])
@login_required
def query():
    requested_user_id = request.args.get('user_id')

    if requested_user_id and int(requested_user_id) != current_user.id: 
        return redirect(url_for('auth.query', user_id=current_user.id))

    user = current_user
    users = User.query.filter(
        and_(
            User.major == user.major,
            User.english_level == user.english_level,
            User.german_level == user.german_level,
            User.semester == user.semester,
            not_(User.id == user.id)
        )
    ).order_by(
        case(
            # Each condition must be a tuple with the first element being the condition and
            # the second element being the value to return when the condition is true
            (and_(
                User.current_group == user.desired_group_1,
                User.current_tut == user.desired_tut_1,
                User.desired_group_1 == user.current_group,
                User.desired_tut_1 == user.current_tut
            ), 0),

            (and_(

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<!-- Head -->
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap -->
    <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
    />
    <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
    />
    
    <title>{% block title %}Home{% endblock %}</title> <!-- Jinja2 Template -->
</head>
  <!-- Link to Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Irish+Grover&display=swap" rel="stylesheet">
    <style>
        /* Custom class for styling the text */
        .custom-text {
            font-family: 'Irish Grover', cursive; /* Apply Irish Grover font */
            text-align: center;                  /* Center the text */
            margin-top: 50px;                    /* Add space above the text */
            font-size: 2rem;                     /* Adjust font size */
            color: #333;                         /* Set text color */
        }
        .custom-form {
            margin-top: 200px; /* Adjust this value as needed */
          }
    </style>

<!-- Body -->
<body class="d-flex flex-column min-vh-100" style="background-color: #ffffff;" >
    <!-- Navbar -->
     <!--
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                <a class="nav-item nav-link" id="logOut" href="/logout">Log Out</a>
                <a class="nav-item nav-link" id="home" href="/">Home</a>
            </div>
        </div>
    </nav>
-->
    <!-- Flashed Messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    <!-- Content Container -->
    <div class="container flex-grow-1">
        {% block content %}
        {% endblock %} 
    </div>
    <footer class="bg-white text-dark text-center py-5 mt-4">
        <p>Developed by <a href="https://www.linkedin.com/in/mohamed-tamer-ba32b51ba/" target="_blank" class="text-primary">Mohamed Tamer</a> and <a href="https://www.linkedin.com/in/adham-jalaal-514992246/" target="_blank" class="text-primary">Adham jalaal</a></p>
        <p class="mb-0">© 2025-2026 matching. All rights reserved.</p>
    </footer>
          

   
      

    <!-- JavaScript (Bootstrap and dependencies) -->
    <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
    ></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
    ></script>
    <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
    ></script>
</body>
</html>

website/templates/home.html
{% extends "base.html" %} <!-- Inheritance -->

{% block title %}MAIN{% endblock %}
{% block content%}
<div class="d-flex align-items-center justify-content-center vh-90">
    <div class="text-center"> 
        <h1 class = "custom-text">Looking for a Group Tutorial?<br> Let’s Connect!</h1>
           <br><br>
        <img src="{{ url_for('static', filename='MEME.jpeg') }}"class="img-fluid" alt="Responsive Image" width="300" height="300" style="border-radius: 15px;">
        <br><br><br><br>
        <a href="/sign-up"><button type="button" class="btn btn-dark mr-4">Sign-up</button></a>
        <a href="/login"><button type="button" class="btn btn-dark">Login</button></a>        
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<form method="POST" class="custom-form">
  <h1 class="custom-text">Looking for a Group Tutorial?<br> Let’s Connect!</h1>
  <br>
  <!-- EMAIL -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
        <div class="input-group">
            <input class="form-control" type="email" placeholder="Email" id="email" name="email">
        </div>
    </div>
  </div>

  <!-- Password -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
        <div class="input-group">
            <input class="form-control" type="password" placeholder="Password" id="password" name="password">
        </div>
        <small class="form-text text-muted mt-1">Write your password so that you won't need to sign up again.</small>
    </div>
  </div>
  <br />
  <button type="submit" class="btn btn-primary d-block mx-auto">Let's GO</button>
  <br>

  <div class="d-flex justify-content-center align-items-center">
    <p class="mb-0 me-2 mr-2">Don't have an account?</p>
    <a class="nav-item nav-link p-0" id="signUp" href="/sign-up">Sign-up</a>
  </div>      
</form>
{% endblock %}

website/templates/query.html
{% extends "base.html" %} 
{% block title %}INFORMATION {% endblock %}
{% block content%}
    <div class="container mt-4" style="overflow-x: auto;">
      <h2>Users Information</h2>  
      <small>Please delete your data if you find the matched person.</small>
      <br><br>  
      <p style = "color: blue;"> *Please note that the table includes only the data for users
        with the same major and the same levels in both English and German.</p>
        <p style = "color: blue;"> *You can connect with the matched person via email or phone number, if provided.</p>
      <!-- Users Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Current Group</th>
            <!-- Added Current Group -->
            <th>Current Tutorial</th>
            <!-- Added Current Tutorial -->
             <th>Desired group 1</th>
             <th>Desired tutorial 1</th>
             <th>Desired group 2</th>
             <th>Desired tutorial 2 </th>
             <th>Phone Number</th>
          </tr>
        </thead>
        <tbody>
          <!-- Loop through the users passed from the route -->
          {% for user in users %}
          <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.current_group }}</td>
            <!-- Shows Current Group -->
            <td>{{ user.current_tut }}</td>
            <td>{{ user.desired_group_1 }}</td>
            <td>{{ user.desired_tut_1 }}</td>
            <td>{{ user.desired_group_2 }}</td>
            <td>{{ user.desired_tut_2 }}</td>
            <!-- Shows Current Tutorial -->
            <td><a href="https://wa.me/+2{{ user.telephone }}">{{ user.telephone }}</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <br><br>
    <h3 class = "text-center">Your data has been added to our database.<br> Try logging in after a while to find the matched person.</h3>
    <br>
    <div class="container d-flex flex-column flex-md-row justify-content-center align-items-center">
        <!-- LOG_OUT button -->
   <a href="{{ url_for('auth.logout') }}" class="btn btn-primary mb-3 mb-md-0 mx-2">Log_out</a>
   <!--UPDATE button -->
   <a href="{{ url_for('auth.update') }}" class="btn btn-primary mb-3 mb-md-0 mx-2">UPDATE my Data</a>
   <!-- DELETE THE DATA -->
   <a href="{{ url_for('auth.delete') }}" class="btn btn-primary">DELETE MY DATA </a>
  </div>

    {% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<form method="POST">
  <h1 class="custom-text">
    Looking for a Group Tutorial?<br />
    Let’s Connect!
  </h1>
  <br />

  <!-- NAME -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3">
      <div class="form-group">
        <input
          class="form-control"
          type="text"
          placeholder="Name"
          name="name"
          id="name"
          value="{{ data['name'] if data['name'] else '' }}"
        />
      </div>
    </div>
  </div>

  <!-- EMAIL -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <input
          class="form-control"
          type="email"
          placeholder="Email"
          id="email"
          name="email"
          value="{{ data['email'] if data['email'] else '' }}"
        />
      </div>
    </div>
  </div>

  <!-- ID -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <input
          class="form-control"
          type="text"
          placeholder="ID"
          id="id"
          name="id"
          value="{{ data['user_id'] if data['user_id'] else '' }}"
        />
      </div>
    </div>
  </div>

  <!-- MAJOR -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <select class="form-control" id="major" name="major">
          <option value="">Select Major</option>
          <option value="First Year Engineering" {% if data['major'] == 'First Year Engineering' %}selected{% endif %}>First Year Engineering</option>
          <option value="MET" {% if data['major'] == 'MET' %}selected{% endif %}>MET</option>
          <option value="IET" {% if data['major'] == 'IET' %}selected{% endif %}>IET</option>
          <option value="MECHA" {% if data['major'] == 'MECHA' %}selected{% endif %}>MECHA</option>
          <option value="CIVIL" {% if data['major'] == 'CIVIL' %}selected{% endif %}>CIVIL</option>
          <option value="PHARMACY" {% if data['major'] == 'PHARMACY' %}selected{% endif %}>PHARMACY</option>
          <option value="LAW" {% if data['major'] == 'LAW' %}selected{% endif %}>LAW</option>
          <option value="BI" {% if data['major'] == 'BI' %}selected{% endif %}>BI</option>
          <option value="BUSINESS" {% if data['major'] == 'BUSINESS' %}selected{% endif %}>Business</option>
          <option value="Applied Arts" {% if data['major'] == 'Applied Arts' %}selected{% endif %}>Applied Arts</option>
          <option value="Production" {% if data['major'] == 'Production' %}selected{% endif %}>Production</option>
        </select>
      </div>
    </div>
  </div>

  <!-- SEMESTER -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <select class="form-control" id="semester" name="semester">
          <option value="">Select Semester</option>
          <option value="1" {% if data['semester'] == 1 %}selected{% endif %}>1</option>
          <option value="2" {% if data['semester'] == 2 %}selected{% endif %}>2</option>
          <option value="3" {% if data['semester'] == 3 %}selected{% endif %}>3</option>
          <option value="4" {% if data['semester'] == 4 %}selected{% endif %}>4</option>
          <option value="5" {% if data['semester'] == 5 %}selected{% endif %}>5</option>
          <option value="6" {% if data['semester'] == 6 %}selected{% endif %}>6</option>
          <option value="7" {% if data['semester'] == 7 %}selected{% endif %}>7</option>
          <option value="8" {% if data['semester'] == 8 %}selected{% endif %}>8</option>
          <option value="9" {% if data['semester'] == 9 %}selected{% endif %}>9</option>
          <option value="10" {% if data['semester'] == 10 %}selected{% endif %}>10</option>
        </select>
      </div>
    </div>
  </div>

  <!-- ENGLISH LEVEL -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <select class="form-control" id="english" name="english">
          <option value="">Select English Level</option>
          <option value="AE" {% if data['english'] == 'AE' %}selected{% endif %}>AE</option>
          <option value="AS" {% if data['english'] == 'AS' %}selected{% endif %}>AS</option>
          <option value="SM" {% if data['english'] == 'SM' %}selected{% endif %}>SM</option>
          <option value="CPS" {% if data['english'] == 'CPS' %}selected{% endif %}>CPS</option>
          <option value="RPW" {% if data['english'] == 'RPW' %}selected{% endif %}>RPW</option>
          <option value="0" {% if data['english'] == '0' %}selected{% endif %}>Completed</option>
        </select>
      </div>
    </div>
  </div>

  <!-- GERMAN LEVEL -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <select class="form-control" id="german" name="german">
          <option value="">Select German Level</option>
          <option value="1" {% if data['german'] == '1' %}selected{% endif %}>1</option>
          <option value="2" {% if data['german'] == '2' %}selected{% endif %}>2</option>
          <option value="3" {% if data['german'] == '3' %}selected{% endif %}>3</option>
          <option value="4" {% if data['german'] == '4' %}selected{% endif %}>4</option>
          <option value="5" {% if data['german'] == '5' %}selected{% endif %}>Completed</option>
        </select>
      </div>
    </div>
  </div>

  <!-- CURRENT GROUP -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <input
          class="form-control"
          type="number"
          placeholder="Current-Group"
          id="current_group"
          name="current_group"
          value="{{ data['current_group'] if data['current_group'] else '' }}"
        />
      </div>
    </div>
  </div>

  <!-- CURRENT TUTORIAL -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <input
          class="form-control"
          type="number"
          placeholder="Current-Tutorial"
          name="current_tutorial"
          id="current_tutorial"
          value="{{ data['current_tutorial'] if data['current_tutorial'] else '' }}"
        />
      </div>
    </div>
  </div>

  <!-- DESIRED GROUP OPTION 1 -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <input
          class="form-control"
          type="number"
          placeholder="Desired-Group (option-1)"
          id="desired_group1"
          name="desired_group1"
          value="{{ data['desired_group1'] if data['desired_group1'] else '' }}"
        />
      </div>
    </div>
  </div>

  <!-- DESIRED TUTORIAL OPTION 1 -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <input
          class="form-control"
          type="number"
          placeholder="Desired-Tutorial (option-1)"
          name="desired_tutorial1"
          id="desired_tutorial1"
          value="{{ data['desired_tutorial1'] if data['desired_tutorial1'] else '' }}"
        />
      </div>
      <small class="form-text text-muted mt-1">
        If you don’t want a specific tutorial, put 0.
      </small>
    </div>
  </div>
  
  <!-- DESIRED GROUP OPTION 2 -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <input
          class="form-control"
          type="number"
          placeholder="Desired-Group (option-2)"
          id="desired_group2"
          name="desired_group2"
          value="{{ data['desired_group2'] if data['desired_group2'] else '' }}"
        />
      </div>
    </div>
  </div>

  <!-- DESIRED TUTORIAL OPTION 2 -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <input
          class="form-control"
          type="number"
          placeholder="Desired-Tutorial (option-2)"
          id="desired_tutorial2"
          name="desired_tutorial2"
          value="{{ data['desired_tutorial2'] if data['desired_tutorial2'] else '' }}"
        />
      </div>
      <small class="form-text text-muted mt-1">If you don’t want a specific tutorial, put 0.</small>
    </div>
  </div>

  <!-- Phone Number -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <input
          class="form-control"
          type="number"
          placeholder="Phone Number (optional)"
          id="phone"
          name="phone"
          value="{{ data['phone'] if data['phone'] else '' }}"
          step="any"
        />
      </div>
      <small class="form-text text-muted mt-1">Providing your phone number will make communication quicker and more convenient. If you prefer not to share it, simply enter 0</small>
    </div>
  </div>

  <!-- Password -->
  <div class="row">
    <div class="col-sm-5 mx-auto mt-3 form-group">
      <div class="input-group">
        <input
          class="form-control"
          type="password"
          placeholder="Password"
          id="password"
          name="password"
          value="{{ data['password'] if data['password'] else '' }}"
        />
      </div>
      <small class="form-text text-muted mt-1">
        Write a password so that you won't need to sign up again.
      </small>
    </div>
  </div>

  <button type="submit" class="btn btn-primary d-block mx-auto">OK</button>
  <br />
  <div class="d-flex justify-content-center align-items-center">
    <p class="mb-0 me-2 mr-2">Already registered?</p>
    <a class="nav-item nav-link p-0" id="login" href="/login">Login</a>
  </div>
  <br /><br />
</form>
{% endblock %}